In [1]:
from generators import *
from rsk import *
from ssiyt import *
from jaquet import *
from permutations import *

In [2]:
dyck_path_to_permutation(np.array([1,1,-1,1,1,1,-1,1,-1,-1,1,-1,-1,-1]))

array([7, 4, 3, 5, 2, 6, 8, 1])

In [3]:
for p in avoiding_permutations(3):
  print(p)

[4 3 2 1]
[4 2 3 1]
[3 4 2 1]
[3 2 4 1]
[2 3 4 1]
